# Generated by Django 2.2.5 on 2020-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('site_visibilty', models.CharField(max_length=8)),
            ],
        ),
    ]
